name: cash_droid
description: Cash Droid Expense Manager


publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.4+4

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_launcher_icons: ^0.11.0
  page_transition: ^2.0.4
  animated_bottom_navigation_bar: ^1.3.0
  fl_chart: ^0.55.2
  date_time_picker: "^2.0.0"
  intl: ^0.17.0
  select_form_field: "^2.0.0"
  scoped_model: ^2.0.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.1
  shared_preferences: ^2.0.10
  file_picker: ^4.3.0
  animations: ^2.0.0
  screenshot: ^1.3.0
  pie_chart: ^5.1.0
  sqflite: ^2.0.1
  share_plus:
  image_gallery_saver: ^1.7.1
  ionicons: ^0.1.2
  community_material_icon: ^5.9.55
  material_design_icons_flutter: ^5.0.6295
  provider: ^6.0.5
  http: ^0.13.4
  google_sign_in: ^5.1.1
  flutter_redux: ^0.8.0
  flutter_facebook_auth: ^5.0.0+2
  facebook_app_events: ^0.19.0
  uuid: ^4.1.0
  sign_in_with_apple: ^4.3.0
  intro_slider: ^3.0.4
  flutter_native_splash: ^1.3.2
  font_awesome_flutter: ^10.4.0
  protobuf: ^2.1.0
  hive: ^2.2.3
  get: ^4.6.1
  path: ^1.8.0
  collection: ^1.15.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"



# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: NexaBold
      fonts:
        - asset: assets/fonts/Nexa-Heavy.ttf
    # - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
